/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(attach_sync_marker.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fb37daae6030c01ffcbea56ca9b7eced)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/attach_sync_marker.h>
// pydoc.h is automatically generated in the build directory
#include <attach_sync_marker_pydoc.h>

void bind_attach_sync_marker(py::module& m)
{

    using attach_sync_marker    = gr::dslwp::attach_sync_marker;


    py::class_<attach_sync_marker, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<attach_sync_marker>>(m, "attach_sync_marker", D(attach_sync_marker))

        .def(py::init(&attach_sync_marker::make),
           D(attach_sync_marker,make)
        )
        



        ;




}








