/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ccsds_pseudo_randomizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e8b4671436bae79b189f9ea0ea3b1437)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/ccsds_pseudo_randomizer.h>
// pydoc.h is automatically generated in the build directory
#include <ccsds_pseudo_randomizer_pydoc.h>

void bind_ccsds_pseudo_randomizer(py::module& m)
{

    using ccsds_pseudo_randomizer    = gr::dslwp::ccsds_pseudo_randomizer;


    py::class_<ccsds_pseudo_randomizer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ccsds_pseudo_randomizer>>(m, "ccsds_pseudo_randomizer", D(ccsds_pseudo_randomizer))

        .def(py::init(&ccsds_pseudo_randomizer::make),
           D(ccsds_pseudo_randomizer,make)
        )
        



        ;




}








