/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ccsds_turbo_encode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a6e867f1d1bab1f559aa374d5aa331d3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/ccsds_turbo_encode.h>
// pydoc.h is automatically generated in the build directory
#include <ccsds_turbo_encode_pydoc.h>

void bind_ccsds_turbo_encode(py::module& m)
{

    using ccsds_turbo_encode    = gr::dslwp::ccsds_turbo_encode;


    py::class_<ccsds_turbo_encode, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ccsds_turbo_encode>>(m, "ccsds_turbo_encode", D(ccsds_turbo_encode))

        .def(py::init(&ccsds_turbo_encode::make),
           D(ccsds_turbo_encode,make)
        )
        



        ;




}








