/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(differential_phase_detection_1bit_cf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(44788bec9ccba644e12dc08d1b869f0a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/differential_phase_detection_1bit_cf.h>
// pydoc.h is automatically generated in the build directory
#include <differential_phase_detection_1bit_cf_pydoc.h>

void bind_differential_phase_detection_1bit_cf(py::module& m)
{

    using differential_phase_detection_1bit_cf    = gr::dslwp::differential_phase_detection_1bit_cf;


    py::class_<differential_phase_detection_1bit_cf, gr::block, gr::basic_block,
        std::shared_ptr<differential_phase_detection_1bit_cf>>(m, "differential_phase_detection_1bit_cf", D(differential_phase_detection_1bit_cf))

        .def(py::init(&differential_phase_detection_1bit_cf::make),
           D(differential_phase_detection_1bit_cf,make)
        )
        



        ;




}








