/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fft_estimator2_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(23aee0ef79740549c714ac55e89a8a9f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/fft_estimator2_cc.h>
// pydoc.h is automatically generated in the build directory
#include <fft_estimator2_cc_pydoc.h>

void bind_fft_estimator2_cc(py::module& m)
{

    using fft_estimator2_cc    = gr::dslwp::fft_estimator2_cc;


    py::class_<fft_estimator2_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fft_estimator2_cc>>(m, "fft_estimator2_cc", D(fft_estimator2_cc))

        .def(py::init(&fft_estimator2_cc::make),
           D(fft_estimator2_cc,make)
        )
        



        ;




}








