/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lrtc_demod2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9345e7c44f9751d1a4227922d5c4e616)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/lrtc_demod2.h>
// pydoc.h is automatically generated in the build directory
#include <lrtc_demod2_pydoc.h>

void bind_lrtc_demod2(py::module& m)
{

    using lrtc_demod2    = gr::dslwp::lrtc_demod2;


    py::class_<lrtc_demod2, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<lrtc_demod2>>(m, "lrtc_demod2", D(lrtc_demod2))

        .def(py::init(&lrtc_demod2::make),
           D(lrtc_demod2,make)
        )
        



        ;




}








