/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lrtc_demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(41a4baf2f36489e223f61b7a17fac314)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/lrtc_demod.h>
// pydoc.h is automatically generated in the build directory
#include <lrtc_demod_pydoc.h>

void bind_lrtc_demod(py::module& m)
{

    using lrtc_demod    = gr::dslwp::lrtc_demod;


    py::class_<lrtc_demod, gr::sync_decimator,
        std::shared_ptr<lrtc_demod>>(m, "lrtc_demod", D(lrtc_demod))

        .def(py::init(&lrtc_demod::make),
           D(lrtc_demod,make)
        )
        



        ;




}








