/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(set_gain_by_tag_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8323d728983fe1d5798ac6c66e67a89f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/set_gain_by_tag_cc.h>
// pydoc.h is automatically generated in the build directory
#include <set_gain_by_tag_cc_pydoc.h>

void bind_set_gain_by_tag_cc(py::module& m)
{

    using set_gain_by_tag_cc    = gr::dslwp::set_gain_by_tag_cc;


    py::class_<set_gain_by_tag_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<set_gain_by_tag_cc>>(m, "set_gain_by_tag_cc", D(set_gain_by_tag_cc))

        .def(py::init(&set_gain_by_tag_cc::make),
           D(set_gain_by_tag_cc,make)
        )
        



        ;




}








