/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(station_info_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9461b5abe07bed87cb6cfceae946e0ed)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/station_info_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <station_info_pdu_pydoc.h>

void bind_station_info_pdu(py::module& m)
{

    using station_info_pdu    = gr::dslwp::station_info_pdu;


    py::class_<station_info_pdu, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<station_info_pdu>>(m, "station_info_pdu", D(station_info_pdu))

        .def(py::init(&station_info_pdu::make),
           D(station_info_pdu,make)
        )
        



        ;




}








