/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(steam_to_vector_moving_window_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ae3fecd13052ff2e8c0f04baf952dfa5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/steam_to_vector_moving_window_cc.h>
// pydoc.h is automatically generated in the build directory
#include <steam_to_vector_moving_window_cc_pydoc.h>

void bind_steam_to_vector_moving_window_cc(py::module& m)
{

    using steam_to_vector_moving_window_cc    = gr::dslwp::steam_to_vector_moving_window_cc;


    py::class_<steam_to_vector_moving_window_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<steam_to_vector_moving_window_cc>>(m, "steam_to_vector_moving_window_cc", D(steam_to_vector_moving_window_cc))

        .def(py::init(&steam_to_vector_moving_window_cc::make),
           D(steam_to_vector_moving_window_cc,make)
        )
        



        ;




}








