/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_to_json_pdu_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d04eda048aa3939850ff2a5ebb67d6a4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/tag_to_json_pdu_c.h>
// pydoc.h is automatically generated in the build directory
#include <tag_to_json_pdu_c_pydoc.h>

void bind_tag_to_json_pdu_c(py::module& m)
{

    using tag_to_json_pdu_c    = gr::dslwp::tag_to_json_pdu_c;


    py::class_<tag_to_json_pdu_c, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<tag_to_json_pdu_c>>(m, "tag_to_json_pdu_c", D(tag_to_json_pdu_c))

        .def(py::init(&tag_to_json_pdu_c::make),
           D(tag_to_json_pdu_c,make)
        )
        



        ;




}








