/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tm_converter2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ac76ee859c9f8ed0ff849bf9f4ecaf0d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/tm_converter2.h>
// pydoc.h is automatically generated in the build directory
#include <tm_converter2_pydoc.h>

void bind_tm_converter2(py::module& m)
{

    using tm_converter2    = gr::dslwp::tm_converter2;


    py::class_<tm_converter2, gr::block, gr::basic_block,
        std::shared_ptr<tm_converter2>>(m, "tm_converter2", D(tm_converter2))

        .def(py::init(&tm_converter2::make),
           D(tm_converter2,make)
        )
        



        ;




}








