/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tm_header_parser.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c3714d1eb26bdb714d7dc435a7952aa6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/tm_header_parser.h>
// pydoc.h is automatically generated in the build directory
#include <tm_header_parser_pydoc.h>

void bind_tm_header_parser(py::module& m)
{

    using tm_header_parser    = gr::dslwp::tm_header_parser;


    py::class_<tm_header_parser, gr::block, gr::basic_block,
        std::shared_ptr<tm_header_parser>>(m, "tm_header_parser", D(tm_header_parser))

        .def(py::init(&tm_header_parser::make),
           D(tm_header_parser,make)
        )
        



        ;




}








