/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_padding_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(685f3328a2047969ae03321880da0fe6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dslwp/vector_padding_cc.h>
// pydoc.h is automatically generated in the build directory
#include <vector_padding_cc_pydoc.h>

void bind_vector_padding_cc(py::module& m)
{

    using vector_padding_cc    = gr::dslwp::vector_padding_cc;


    py::class_<vector_padding_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<vector_padding_cc>>(m, "vector_padding_cc", D(vector_padding_cc))

        .def(py::init(&vector_padding_cc::make),
           D(vector_padding_cc,make)
        )
        



        ;




}








